{% set name = "qe-tools" %}
{% set version = "1.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "61244925c7b01ea7c23bd3474dc110e756092cc6a880e9969557e3316bb32045"

build:
  number: 0
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - future
    - numpy
    - python

test:
  imports:
    - qe_tools
    - qe_tools.parsers
    - qe_tools.utils

about:
  home: "https://github.com/aiidateam/qe-tools"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "A set of useful tools to manage Quantum ESPRESSO files"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - chrisjsewell
