{% set name = "prospector" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "ea910794b53cfefcb5dfb6b4eb0323e42d1a88132e165b85b016cc7f0b6ae635"

build:
  number: 0
  noarch: python
  entry_points:
    - prospector = prospector.run:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - astroid ==2.3.3
    - dodgy >=0.1.9
    - mccabe >=0.5.0
    - pep8-naming >=0.3.3,<=0.4.1
    - pycodestyle <=2.5.0,>=2.0.0  # note this should be <= 2.4.0, but conflicts with flake8>=3.7
    - pydocstyle >=2.0.0
    - pyflakes <2.2.0,>=0.8.1
    - pylint ==2.4.4
    - pylint-celery ==0.3
    - pylint-django >=2.0.11,<=2.0.12  # this should be 2.0.12, but not yet available on conda
    - pylint-flask ==0.6
    - pylint-plugin-utils >=0.2.6
    - python
    - pyyaml
    - requirements-detector >=0.6
    - setoptconf >=0.2.0

test:
  imports:
    - prospector
    - prospector.config
    - prospector.formatters
    - prospector.profiles
    - prospector.tools
    - prospector.tools.dodgy
    # - prospector.tools.frosted
    - prospector.tools.mccabe
    # - prospector.tools.mypy
    - prospector.tools.pep257
    - prospector.tools.pep8
    - prospector.tools.profile_validator
    - prospector.tools.pyflakes
    - prospector.tools.pylint
    # - prospector.tools.pyroma
    # - prospector.tools.vulture
  commands:
    - prospector --help

outputs:
  - name: prospector
  - name: prospector.add_ons
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - frosted >=1.4.1
        - pyroma >=2.4
        - vulture >=0.6,<0.25
        - mypy >=0.600

about:
  home: "http://prospector.readthedocs.io"
  license: "GNU General Public v2 or later (GPLv2+)"
  license_family: "GPL2"
  license_file: ""
  summary: "Prospector: python static analysis tool"
  doc_url: ""
  dev_url: "https://github.com/PyCQA/prospector"

extra:
  recipe-maintainers:
    - chrisjsewell
